name: Cofre Digital - Deploy Automatizado

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Construir Container Image
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixando o codigo no robo
        uses: actions/checkout@v4

      - name: 2. Testando a construcao da caixa segura (Docker)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false # Garante que nao precisa de login para testar!

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Realizando o Deploy Seguro
        run: |
          echo "Iniciando deploy para o ambiente de testes (STAGING)..."
          echo "Buscando dados salvos no cofre de forma segura..."
          echo "DB_HOST=${{ secrets.STAGING_DB_HOST }}" >> staging.env
          echo "DB_USER=${{ secrets.STAGING_DB_USER }}" >> staging.env
          echo "Deploy em Staging concluido com sucesso!"
