name: Cofre Digital - Deploy Automatizado

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Construir Container Image
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixando o codigo no robo
        uses: actions/checkout@v4

      - name: 2. Testando a construcao da caixa segura (Docker)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
